### ISSUE TITLE
The result is not a match from the bcrypt-generator.com

### ISSUE THREAD

**Issue by JerryCheng1** [hilch/Bcrypt.cpp#3]
What is the reason? Is there a risk of being decrypted?
```
Hash: $2b$10$nJ3McGQr0jkabP8Zi1V7tu23qrtq347IbtcCNniOJ2nFkcgj9GZdu
"jerry123312" : 1
"wrong" : 0
```

**Comment by shilch** [comment]
Hello @JerryCheng1, not sure if I understand you correctly.  
Do bcrypt-generator.com and this library yield different hash values for the same input? In that case, it should be noted that the generation of a bcrypt hash is non-deterministic as each hash includes a random salt value that is incorporated into the final output. This protects against attacks via rainbow tables (i.e. lookup tables hash -> preimage).

**Comment by JerryCheng1** [comment]
> Hello @JerryCheng1, not sure if I understand you correctly. Do bcrypt-generator.com and this library yield different hash values for the same input? In that case, it should be noted that the generation of a bcrypt hash is non-deterministic as each hash includes a random salt value that is incorporated into the final output. This protects against attacks via rainbow tables (i.e. lookup tables hash -> preimage).


Hello, @shilch 
Yes, the library can yield different hash and hash can be matched by the library. But doing bcrypt-generator.com checker is failed to matched the bcrypt hash was yield by the library. Is the reason that the salt is different?
The library yield one of hash:
```
$2b$10$nJ3McGQr0jkabP8Zi1V7tu23qrtq347IbtcCNniOJ2nFkcgj9GZdu
```
The string:
```
jerry123312
```
 bcrypt-generator.com checker shows: Not a match!

**Comment by hilch** [comment]
the implementation from OpenBSD is not compatible with the most commonly used algorithms in web services. I replaced the code by the implementation used by project node.bcrypt.

**Comment by JerryCheng1** [comment]
您的邮件已收到。祝您生活愉快！
