### ISSUE TITLE
why i hash same password，result unchanged？

### ISSUE THREAD

**Issue by Jerry-Lam** [hilch/Bcrypt.cpp#5]
I running your library on wsl2 unbutu 22.04.1
````
#include "bcrypt.h"
#include <iostream>
int main()
{

    std::string password = "123456";

    std::string hash = bcrypt::generateHash(password, 12);

    std::cout << "Hash: " << hash << std::endl;

    return 0;
}
````

![image](https://user-images.githubusercontent.com/47733636/190982268-43d58281-fb01-4ad6-a5c5-6da6301a9df1.png)

**Comment by Jerry-Lam** [comment]
Seems not auto-gen a salt

**Comment by hilch** [comment]
Thanks for your input. Try again, please.
